openapi: 3.0.0
info:
  title: "REST API to TON Console"
  version: 0.0.1
  contact:
    name: "Support"
    email: "contact@tonaps.org"

servers:
  - url: "http://localhost:8888"

paths:
  /api/v1/auth/tg:
    post:
      description: "Auth via telegram"
      operationId: authViaTG
      tags:
        - auth
      requestBody:
        $ref: "#/components/requestBodies/TgAuthInput"
      responses:
        '200':
          $ref: '#/components/responses/Ok'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/auth/ton-proof/generate_payload:
    post:
      description: "Generate payload for TON Connect"
      operationId: authGeneratePayload
      tags:
        - auth
      responses:
        '200':
          $ref: '#/components/responses/GeneratePayload'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/auth/ton-proof/check_proof:
    post:
      description: "Auth via TON Connect"
      operationId: authViaTonConnect
      tags:
        - auth
      requestBody:
        $ref: "#/components/requestBodies/TonProofInput"
      responses:
        '200':
          $ref: '#/components/responses/Ok'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
  
  /api/v1/account/logout:
    post:
      description: "Logout from the system"
      operationId: accountLogout
      security:
        - JWTAuth: [ "common" ]
      tags:
        - account
      responses:
        '200':
          $ref: '#/components/responses/Ok'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
  
  /api/v1/tiers:
    get:
      description: "Get active tiers"
      operationId: getTiers
      security:
        - JWTAuth: [ "common" ]
      tags:
        - tier
      responses:
        '200':
          $ref: '#/components/responses/Tiers'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
  
  /api/v1/projects:
    get:
      description: "Get user's project"
      operationId: getProjects
      security:
        - JWTAuth: [ "common" ]
      tags:
        - project
      responses:
        '200':
          $ref: '#/components/responses/Projects'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/project/{id}:
    patch:
      description: "Get user's project"
      operationId: getProjects
      security:
        - JWTAuth: [ "common" ]
      tags:
        - project
      parameters:
        - $ref: '#/components/parameters/projectID'
      requestBody:
        $ref: "#/components/requestBodies/ProjectInputUpdate"
      responses:
        '200':
          $ref: '#/components/responses/Ok'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'


components:
  parameters:
    tokenID:
      description: Token ID
      in: path
      name: id
      required: true
      schema:
        type: integer
        format: int64
    projectID:
      description: Project ID
      in: path
      name: id
      required: true
      schema:
        type: integer
        format: int64
  
  requestBodies:
    TgAuthInput:
      description: "Data that is expected from Telegram"
      content:
        application/json:
          schema:
            type: object
            required:
              - id
              - hash
              - auth_date
            properties:
              id:
                type: integer
                format: int64
                example: "1261871881"
              first_name:
                type: string
                example: "Test"
              photo_url:
                type: string
                example: "Testov"
              username:
                type: string
                example: "testov"
              hash:
                type: string
                example: "cd0e201bf7328535343301f428e51f01084a3e2a3822f4843d86b540bbebfe15"
              auth_date:
                type: integer
                format: int64
                example: "1678275313"
    TonProofInput:
      description: "Data that is expected from TON Connect"
      content:
        application/json:
          schema:
            type: object
            required:
              - address
              - proof
            properties:
              address:
                type: string
                example: "0:97146a46acc2654y27947f14c4a4b14273e954f78bc017790b41208b0043200b"
              proof:
                type: object
                properties:
                  timestamp:
                    type: integer
                    format: int64
                    example: "1678275313"
                  domain:
                    type: object
                    properties:
                      length_bytes:
                        type: integer
                        format: uint32
                      value:
                        type: string
                  signature:
                    type: string
                  payload:
                    type: string
                    example: "84jHVNLQmZsAAAAAZB0Zryi2wqVJI-KaKNXOvCijEi46YyYzkaSHyJrMPBMOkVZa"
                  state_init:
                    type: string
    ProjectInputUpdate:
      description: "Data that is expected"
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              name:
                type: string
                example: "Test Project"
              tier_id:
                type: integer
                format: int64
                example: 1

  schemas:
    Ok:
      type: object
      required:
        - ok
      properties:
        ok:
          type: boolean
          example: true
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: "Error message"
    User:
      type: object
      required:
        - id
        - is_ban
        - date_create
      properties:
        id:
          type: integer
          format: int64
          example: "1464363297"
        tg_id:
          type: integer
          format: int64
          example: "1260831881"
          description: "ID from the Telegram service"
        wallet_address:
          type: string
          example: "0:97146a46acc2654y27947f14c4a4b14273e954f78bc017790b41208b0043200b"
          description: "TON wallet address"
        first_name:
          type: string
          example: "Test"
        last_name:
          type: string
          example: "Testov"
        avatar:
          type: string
          example: "https://test.io/my_face.png"
        is_ban:
          type: boolean
          default: false
          example: false
        token:
          type: string
          description: "Authorization token"
        date_create:
          type: integer
          format: int64
          example: 1678275313
    Webhook:
      type: object
      required:
        - id
        - user_id
        - app_id
        - payload_url
        - secret
        - active
        - type_actions
        - date_create
      properties:
        id:
          type: integer
          format: int64
          example: 1
        user_id:
          type: integer
          format: int64
          example: 1464363297
        app_id:
          type: integer
          format: int64
          example: 2465363097
        payload_url:
          type: string
          example: "http://tonapi.io/callback"
        secret:
          type: string
          example: "it's my secret"
        addresses:
          type: array
          items:
            type: string
          example: [
            "0:15d570f9c0c67e8e6d40f5c69be049a247dd6c0e841d31ac8dcc3edf4a57d057",
            "0:85d570f9c0c67e8e6v40f2c69be049a217dd6c0f841d31ac8dcc3edf4a57d057"
          ]
        active:
          type: boolean
          example: true
        type_actions:
          type: array
          items:
            type: string
            example: "account_event"
          enum:
            - "account_event"
        date_create:
          type: integer
          format: int64
          example: 1678275313
    AppToken:
      type: object
      required:
        - id
        - user_id
        - app_id
        - tier
        - token
        - is_ban
        - active
        - date_create
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          format: int64
          example: 1464363297
        app_id:
          type: integer
          format: int64
          example: 2465363097
        tier:
          $ref: '#/components/schemas/Tier'
        token:
          type: string
          example: "AFWRUVK5QHVRFFAAAAACNAS5QU22SHA2D4SMH3SFJOOQB5PCBU7Z7KDDWKQT5KI2YNABHBI"
        is_ban:
          type: boolean
          example: false
        active:
          type: boolean
          example: true
        date_create:
          type: integer
          format: int64
          example: 1678275313
    Tier:
      type: object
      required:
        - id
        - name
        - rpc
        - burst
        - ton_price
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Test tier"
        burst:
          type: integer
          example: 1
        rpc:
          type: number
          example: 5
        ton_price:
          type: integer
          example: 100
    AppTier:
      type: object
      required:
        - id
        - name
        - rpc
        - burst
        - ton_price
        - active
        - date_create
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Test tier"
        burst:
          type: integer
          example: 1
        rpc:
          type: number
          example: 5
        ton_price:
          type: integer
          example: 100
        active:
          type: boolean
          example: true
        date_create:
          type: string
          example: "2023-03-23"
    
    Project:
      type: object
      required:
        - id
        - name
        - avatar
        - active
        - date_create
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Test project"
        tier:
          $ref: '#/components/schemas/AppTier'
        avatar:
          type: string
          example: "https://tonapi.io/static/test.png"
        date_create:
          type: string
          example: "2023-03-23"
  
  responses:
    NotFound:
      description: "The specified resource was not found"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: "Something went wrong on server side"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: "Something went wrong on client side"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    UnauthorizedError:
      description: "Access token is missing or invalid"
    Ok:
      description: "Ok"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Ok'
    GeneratePayload:
      description: "Payload for TON Connect"
      content:
        application/json:
          schema:
            type: object
            required:
              - payload
            properties:
              payload:
                type: string
                example: "84jHVNLQmZsAAAAAZB0Zryi2wqVJI-KaKNXOvCijEi46YyYzkaSHyJrMPBMOkVZa"
    Tiers:
      description: "Active tiers"
      content:
        application/json:
          schema:
            required:
              - items
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '#/components/schemas/Tier'
    Projects:
      description: "User projects"
      content:
        application/json:
          schema:
            required:
              - items
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
  
  
  securitySchemes:
    JWTAuth:
      description: "JWT token authorization"
      type: http
      scheme: bearer
      bearerFormat: JWT
